# Generated by Django 6.1 on 2026-08-21 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_fidelity_tests(apps, schema_editor):
    FidelityTest = apps.get_model("core", "FidelityTest")
    TransparencyRequest = apps.get_model("core", "TransparencyRequest")
    Payment = apps.get_model("core", "Payment")
    status_map = {
        "PENDING": "PENDING",
        "PASSED": "ACCEPTED",
        "FAILED": "REFUSED",
        "EXPIRED": "EXPIRED",
    }
    for legacy in FidelityTest.objects.all().iterator():
        TransparencyRequest.objects.create(
            requester_id=legacy.initiator_id,
            target_phone=legacy.target_phone,
            payment_id=legacy.payment_id,
            token=legacy.token,
            status=status_map.get(legacy.status, "EXPIRED"),
            declared_status="",
            declared_partner_name=legacy.submitted_partner_name,
            expires_at=legacy.expires_at,
            created_at=legacy.created_at,
        )
    Payment.objects.filter(service_type="FIDELITY_TEST").update(
        service_type="TRANSPARENCY_REQUEST"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_financial_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransparencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_phone', models.CharField(max_length=15)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REFUSED', 'Refused'), ('EXPIRED', 'Expired'), ('BLOCKED', 'Blocked'), ('REPORTED', 'Reported')], default='PENDING', max_length=20)),
                ('declared_status', models.CharField(blank=True, choices=[('ENGAGED', 'En couple'), ('AVAILABLE', 'Disponible'), ('PREFER_NOT_TO_ANSWER', 'Préfère ne pas répondre')], max_length=30)),
                ('declared_partner_name', models.CharField(blank=True, max_length=100)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='phoneverificationaccess',
            new_name='core_phonev_user_id_6d4419_idx',
            old_name='core_phonev_user_id_6f0b0d_idx',
        ),
        migrations.AddField(
            model_name='declaration',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='declaration',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='declaration',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='declaration',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Relation privée'), ('PUBLIC_CERTIFIED', 'Statut certifié public')], default='PRIVATE', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_status_searchable',
            field=models.BooleanField(default=False, help_text='Autorise la consultation publique du statut certifié.'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service_type',
            field=models.CharField(choices=[('VERIFICATION', 'Vérification'), ('DECLARATION', 'Déclaration'), ('TRANSPARENCY_REQUEST', 'Demande de Transparence'), ('FIDELITY_TEST', 'Test de fidélité (historique)'), ('ALLIANCE_VIP', 'Alliance VIP')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='transparencyrequest',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transparency_requests', to='core.payment'),
        ),
        migrations.AddField(
            model_name='transparencyrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transparency_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            migrate_legacy_fidelity_tests,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='fidelitytest',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='fidelitytest',
            name='payment',
        ),
        migrations.DeleteModel(
            name='FidelityTest',
        ),
        migrations.AddIndex(
            model_name='transparencyrequest',
            index=models.Index(fields=['requester', 'target_phone', 'status'], name='core_transp_request_a54d56_idx'),
        ),
        migrations.AddIndex(
            model_name='transparencyrequest',
            index=models.Index(fields=['target_phone', 'created_at'], name='core_transp_target__5e06d9_idx'),
        ),
    ]
