# Generated by Django 6.1 on 2026-08-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transparencyrequest_remove_fidelitytest_initiator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('ENDED', 'Ended')], default='PENDING', max_length=20),
        ),
    ]
