# Generated by Django 6.1 on 2026-08-21 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_declaration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_PARTNER', 'En attente du partenaire'), ('ACTIVE', 'Active'), ('REFUSED', 'Refusée'), ('ENDED', 'Terminée')], default='PENDING_PARTNER', max_length=20)),
                ('initiator_consented_at', models.DateTimeField()),
                ('partner_consented_at', models.DateTimeField(blank=True, null=True)),
                ('initiator_badge_public', models.BooleanField(default=False)),
                ('partner_badge_public', models.BooleanField(default=False)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('declaration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alliance', to='core.declaration')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alliances_started', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alliances_received', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='alliance', to='core.payment')),
            ],
            options={
                'indexes': [models.Index(fields=['initiator', 'status'], name='core_allian_initiat_20de49_idx'), models.Index(fields=['partner', 'status'], name='core_allian_partner_75e21b_idx')],
            },
        ),
    ]
