# Generated by Django 6.1 on 2026-08-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_email_verified_at_user_phone_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverificationaccess',
            name='used_at',
            field=models.DateTimeField(blank=True, help_text='Horodatage de la consultation facturée (usage unique par paiement).', null=True),
        ),
    ]
